// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./api-bodies.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript type **WikiName**
 * @see {@link ./api-bodies.as:12:13}
 */
export type WikiName = string
declare namespace WikiName {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeFinal<WikiName>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof WikiName>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  const toExampleData: (() => any) | undefined
}

/**
 * Atscript type **DocHandle**
 * @see {@link ./api-bodies.as:19:13}
 */
export type DocHandle = string
declare namespace DocHandle {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeFinal<DocHandle>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof DocHandle>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  const toExampleData: (() => any) | undefined
}

/**
 * Atscript type **AgentList**
 * @see {@link ./api-bodies.as:25:13}
 */
export type AgentList = string
declare namespace AgentList {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeFinal<AgentList>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AgentList>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  const toExampleData: (() => any) | undefined
}

/**
 * Atscript interface **AddDocBody**
 * @see {@link ./api-bodies.as:28:18}
 */
export declare class AddDocBody {
  title: string
  category: string
  tags?: string[]
  body?: string
  content?: string
  text?: string
  raw?: string
  importantSections?: string[]
  suppressMergeWarn?: string[]
  suppressLint?: string[]
  dryRun?: boolean
  wiki?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof AddDocBody, AddDocBody>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AddDocBody>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **UpdateDocBody**
 * @see {@link ./api-bodies.as:55:18}
 */
export declare class UpdateDocBody {
  title?: string
  category?: string
  tags?: string[]
  body?: string
  content?: string
  text?: string
  raw?: string
  appendBody?: string
  append?: string
  importantSections?: string[]
  suppressMergeWarn?: string[]
  suppressLint?: string[]
  dryRun?: boolean
  wiki?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof UpdateDocBody, UpdateDocBody>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof UpdateDocBody>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **RenameDocBody**
 * @see {@link ./api-bodies.as:78:18}
 */
export declare class RenameDocBody {
  newId?: string
  to?: string
  name?: string
  wiki?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof RenameDocBody, RenameDocBody>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof RenameDocBody>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **CreateWikiBody**
 * @see {@link ./api-bodies.as:86:18}
 */
export declare class CreateWikiBody {
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof CreateWikiBody, CreateWikiBody>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof CreateWikiBody>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **LogAddBody**
 * @see {@link ./api-bodies.as:92:18}
 */
export declare class LogAddBody {
  op?: "ingest" | "query" | "lint" | "note"
  doc?: string
  details?: string
  wiki?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof LogAddBody, LogAddBody>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof LogAddBody>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end