// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./link.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **Link**
 * @see {@link ./link.as:3:18}
 */
export declare class Link {
  fromId: string
  toId: string
  linkText?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Link, Link>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Link>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "fromId": string
    "toId": string
    "linkText"?: string
  }
  static __ownProps: {
    "fromId": string
    "toId": string
    "linkText"?: string
  }
  
  static __pk: {
    fromId: string
    toId: string
  }
}
// prettier-ignore-end